### ISSUE TITLE
move latest builds to broken: python shouldn't be a dependency of ninja

### ISSUE THREAD

**Issue by looooo** [conda-forge/ninja-feedstock#18]
Not sure why this changed but this leads to a lot of troubles for compiled packages with python-bindings. eg: 
https://github.com/conda-forge/ifcopenshell-feedstock/pull/7

**Comment by looooo** [comment]
@conda-forge/core

**Comment by beckermr** [comment]
see conda-forge/cf-mark-broken

**Comment by looooo** [comment]
https://github.com/conda-forge/cf-mark-broken/pull/18

**Comment by CJ-Wright** [comment]
Can this be closed?
